# Sistemas Lineares Aplicados — Placa Metálica

**Dupla:** Luiz Gabriel e Gabriel Lima

Este notebook é o bônus da atividade: ele monta automaticamente a matriz do sistema e resolve com `numpy.linalg.solve`.

## Ideia do modelo

Cada ponto interno da placa é calculado pela média dos quatro vizinhos:

$$T = \frac{T_{cima}+T_{baixo}+T_{esq}+T_{dir}}{4}$$

Reorganizando, fica no formato de sistema linear:

$$4T_i - \text{vizinhos internos} = \text{bordas conhecidas}$$

In [1]:
import numpy as np

def resolver_placa(n=3, topo=100, base=0, esquerda=75, direita=50):
    N = n * n
    A = np.zeros((N, N))
    b = np.zeros(N)

    def idx(i, j):
        return i * n + j

    for i in range(n):
        for j in range(n):
            k = idx(i, j)
            A[k, k] = 4

            # vizinho de cima
            if i == 0:
                b[k] += topo
            else:
                A[k, idx(i-1, j)] = -1

            # vizinho de baixo
            if i == n - 1:
                b[k] += base
            else:
                A[k, idx(i+1, j)] = -1

            # vizinho da esquerda
            if j == 0:
                b[k] += esquerda
            else:
                A[k, idx(i, j-1)] = -1

            # vizinho da direita
            if j == n - 1:
                b[k] += direita
            else:
                A[k, idx(i, j+1)] = -1

    solucao = np.linalg.solve(A, b).reshape(n, n)
    return A, b, solucao


In [2]:
A, b, caso_original = resolver_placa()
print('Caso original:')
print(np.round(caso_original, 2))

Caso original:
[[78.57 76.12 69.64]
 [63.17 56.25 52.46]
 [42.86 33.26 33.93]]


In [3]:
_, _, experimento = resolver_placa(topo=200, esquerda=0)
print('Experimento topo = 200 e esquerda = 0:')
print(np.round(experimento, 2))

print('\nDiferença em relação ao caso original:')
print(np.round(experimento - caso_original, 2))

Experimento topo = 200 e esquerda = 0:
[[ 89.29 114.73 107.14]
 [ 42.41  62.5   63.84]
 [ 17.86  29.02  35.71]]

Diferença em relação ao caso original:
[[ 10.71  38.62  37.5 ]
 [-20.76   6.25  11.38]
 [-25.    -4.24   1.79]]


## Experimento com topo sendo 200 e a esquerda 0

No caso original, as maiores temperaturas ficaram na parte superior da placa, pois o topo está a 100°C. No experimento, a região de cima muda mais porque o topo sobe para 200°C. Já os pontos próximos da esquerda esfriam, pois a borda esquerda passa de 75°C para 0°C.