# 📘 Eliminação de Gauss — Resolução de Sistemas Lineares

**Disciplina:** Cálculo Numérico / Álgebra Linear  

**Alunos:** Luiz Gabriel e Gabriel Lima

**Método:** Eliminação de Gauss  

**Objetivo:** Implementar o método e aplicá-lo na resolução de sistemas lineares da forma **Ax = b**


---

## 📂 Parte 1 — Resolução Manual

### Sistema dado:

$$
\begin{cases}
2x + y - z = 8 \\
-3x - y + 2z = -11 \\
-2x + y + 2z = -3
\end{cases}
$$

---

### Passo 1 — Matriz Aumentada

Montamos a matriz aumentada $[A|b]$:

$$
\left[\begin{array}{ccc|c}
2 & 1 & -1 & 8 \\
-3 & -1 & 2 & -11 \\
-2 & 1 & 2 & -3
\end{array}\right]
$$

---

### Passo 2 — Eliminação de Gauss (zerando coluna 1)

**Pivô:** elemento $a_{11} = 2$

**Operação $L_2 \leftarrow L_2 + \frac{3}{2}L_1$:**

$$m_{21} = \frac{-3}{2} = -1{,}5$$

Nova $L_2$: $[-3 + 1{,}5 \cdot 2,\ -1 + 1{,}5 \cdot 1,\ 2 + 1{,}5 \cdot (-1),\ -11 + 1{,}5 \cdot 8] = [0,\ 0{,}5,\ 0{,}5,\ 1]$

**Operação $L_3 \leftarrow L_3 + L_1$:**

$$m_{31} = \frac{-2}{2} = -1$$

Nova $L_3$: $[-2 + 2,\ 1 + 1,\ 2 + (-1),\ -3 + 8] = [0,\ 2,\ 1,\ 5]$

Matriz após 1ª etapa:

$$
\left[\begin{array}{ccc|c}
2 & 1 & -1 & 8 \\
0 & 0{,}5 & 0{,}5 & 1 \\
0 & 2 & 1 & 5
\end{array}\right]
$$

---

### Passo 3 — Eliminação (zerando coluna 2)

**Pivô:** elemento $a_{22} = 0{,}5$

**Operação $L_3 \leftarrow L_3 - 4 \cdot L_2$:**

$$m_{32} = \frac{2}{0{,}5} = 4$$

Nova $L_3$: $[0,\ 2 - 4 \cdot 0{,}5,\ 1 - 4 \cdot 0{,}5,\ 5 - 4 \cdot 1] = [0,\ 0,\ -1,\ 1]$

**Forma triangular superior:**

$$
\left[\begin{array}{ccc|c}
2 & 1 & -1 & 8 \\
0 & 0{,}5 & 0{,}5 & 1 \\
0 & 0 & -1 & 1
\end{array}\right]
$$

---

### Passo 4 — Substituição Regressiva

**Da equação 3:**
$$-z = 1 \Rightarrow z = -1$$

**Da equação 2:**
$$0{,}5y + 0{,}5(-1) = 1 \Rightarrow 0{,}5y = 1{,}5 \Rightarrow y = 3$$

**Da equação 1:**
$$2x + 3 - (-1) = 8 \Rightarrow 2x = 4 \Rightarrow x = 2$$

### ✅ Solução: $x = 2,\ y = 3,\ z = -1$

---
## 💻 Parte 2 — Implementação em Python

In [1]:
import numpy as np
import copy

In [2]:
def eliminacao_gauss(A, b):
    """
    Resolve o sistema linear Ax = b pelo método de Eliminação de Gauss.

    Parâmetros:
        A (list ou np.ndarray): Matriz de coeficientes (n x n)
        b (list ou np.ndarray): Vetor de termos independentes (n)

    Retorna:
        x (np.ndarray): Vetor solução
    """
    # Converte para float para evitar divisão inteira
    A = np.array(A, dtype=float)
    b = np.array(b, dtype=float)
    n = len(b)

    # Monta a matriz aumentada [A|b]
    Ab = np.hstack([A, b.reshape(-1, 1)])

    print("=" * 50)
    print("Matriz aumentada inicial [A|b]:")
    print(Ab)
    print()

    # ─────────────────────────────────────
    # ETAPA 1: Eliminação (forma triangular)
    # ─────────────────────────────────────
    for col in range(n):
        pivo = Ab[col, col]

        # Verifica pivô nulo (sistema singular ou infinitas soluções)
        if abs(pivo) < 1e-12:
            raise ValueError(
                f"Pivô nulo na coluna {col}! "
                "O sistema pode ser singular ou ter infinitas soluções."
            )

        # Zera os elementos abaixo do pivô
        for linha in range(col + 1, n):
            fator = Ab[linha, col] / pivo
            Ab[linha, :] = Ab[linha, :] - fator * Ab[col, :]

        print(f"Após zerar coluna {col + 1}:")
        print(Ab)
        print()

    print("Forma triangular superior obtida!")
    print("=" * 50)
    print()

    # ─────────────────────────────────────
    # ETAPA 2: Substituição Regressiva
    # ─────────────────────────────────────
    x = np.zeros(n)

    for i in range(n - 1, -1, -1):
        soma = sum(Ab[i, j] * x[j] for j in range(i + 1, n))
        x[i] = (Ab[i, n] - soma) / Ab[i, i]

    return x

---
## 📊 Parte 3 — Teste com o Sistema da Parte 1

In [3]:
# Sistema: 2x + y - z = 8 | -3x - y + 2z = -11 | -2x + y + 2z = -3
A1 = [
    [ 2,  1, -1],
    [-3, -1,  2],
    [-2,  1,  2]
]
b1 = [8, -11, -3]

print("Sistema: 2x + y - z = 8 | -3x - y + 2z = -11 | -2x + y + 2z = -3")
print()

solucao_gauss = eliminacao_gauss(A1, b1)
solucao_numpy = np.linalg.solve(A1, b1)

print("🔵 Solução pelo Método de Gauss:")
print(f"   x = {solucao_gauss[0]:.6f}")
print(f"   y = {solucao_gauss[1]:.6f}")
print(f"   z = {solucao_gauss[2]:.6f}")
print()
print("🟢 Solução pelo numpy.linalg.solve:")
print(f"   x = {solucao_numpy[0]:.6f}")
print(f"   y = {solucao_numpy[1]:.6f}")
print(f"   z = {solucao_numpy[2]:.6f}")
print()
print("✅ Resultados coincidem?", np.allclose(solucao_gauss, solucao_numpy))

Sistema: 2x + y - z = 8 | -3x - y + 2z = -11 | -2x + y + 2z = -3

Matriz aumentada inicial [A|b]:
[[  2.   1.  -1.   8.]
 [ -3.  -1.   2. -11.]
 [ -2.   1.   2.  -3.]]

Após zerar coluna 1:
[[ 2.   1.  -1.   8. ]
 [ 0.   0.5  0.5  1. ]
 [ 0.   2.   1.   5. ]]

Após zerar coluna 2:
[[ 2.   1.  -1.   8. ]
 [ 0.   0.5  0.5  1. ]
 [ 0.   0.  -1.   1. ]]

Após zerar coluna 3:
[[ 2.   1.  -1.   8. ]
 [ 0.   0.5  0.5  1. ]
 [ 0.   0.  -1.   1. ]]

Forma triangular superior obtida!

🔵 Solução pelo Método de Gauss:
   x = 2.000000
   y = 3.000000
   z = -1.000000

🟢 Solução pelo numpy.linalg.solve:
   x = 2.000000
   y = 3.000000
   z = -1.000000

✅ Resultados coincidem? True


---
## 🧠 Parte 4 — Análise

**1. O resultado coincide com o obtido pelo numpy?**  
Sim. Ambos os métodos retornam $x = 2,\ y = 3,\ z = -1$, confirmando que a implementação está correta. Pequenas diferenças de arredondamento (ordem de $10^{-15}$) são normais em operações de ponto flutuante.

**2. Qual etapa foi mais difícil de implementar?**  
A **substituição regressiva** exige mais atenção: é necessário acumular a soma dos termos já calculados e dividir pelo coeficiente da variável atual. A eliminação em si é mais mecânica (loop duplo com cálculo do fator multiplicador).

**3. O método funciona para qualquer sistema?**  
Não. O método de Gauss simples (sem pivotamento) pode falhar quando o **pivô é zero ou muito próximo de zero**, o que ocorre em sistemas singulares (sem solução ou com infinitas soluções) ou mal-condicionados. Técnicas como o **pivotamento parcial** (trocar a linha do pivô pela de maior valor absoluto na coluna) tornam o método mais robusto.

---
## 🚀 Parte 5 — Desafio

### Sistema:
$$
\begin{cases}
x + y + z = 6 \\
2x + 3y + z = 10 \\
x + 2y + 3z = 13
\end{cases}
$$

In [4]:
A2 = [
    [1, 1, 1],
    [2, 3, 1],
    [1, 2, 3]
]
b2 = [6, 10, 13]

print("Sistema desafio: x + y + z = 6 | 2x + 3y + z = 10 | x + 2y + 3z = 13")
print()

sol_gauss_2  = eliminacao_gauss(A2, b2)
sol_numpy_2  = np.linalg.solve(A2, b2)

print("🔵 Solução pelo Método de Gauss:")
print(f"   x = {sol_gauss_2[0]:.6f}")
print(f"   y = {sol_gauss_2[1]:.6f}")
print(f"   z = {sol_gauss_2[2]:.6f}")
print()
print("🟢 Solução pelo numpy.linalg.solve:")
print(f"   x = {sol_numpy_2[0]:.6f}")
print(f"   y = {sol_numpy_2[1]:.6f}")
print(f"   z = {sol_numpy_2[2]:.6f}")
print()
print("✅ Resultados coincidem?", np.allclose(sol_gauss_2, sol_numpy_2))

Sistema desafio: x + y + z = 6 | 2x + 3y + z = 10 | x + 2y + 3z = 13

Matriz aumentada inicial [A|b]:
[[ 1.  1.  1.  6.]
 [ 2.  3.  1. 10.]
 [ 1.  2.  3. 13.]]

Após zerar coluna 1:
[[ 1.  1.  1.  6.]
 [ 0.  1. -1. -2.]
 [ 0.  1.  2.  7.]]

Após zerar coluna 2:
[[ 1.  1.  1.  6.]
 [ 0.  1. -1. -2.]
 [ 0.  0.  3.  9.]]

Após zerar coluna 3:
[[ 1.  1.  1.  6.]
 [ 0.  1. -1. -2.]
 [ 0.  0.  3.  9.]]

Forma triangular superior obtida!

🔵 Solução pelo Método de Gauss:
   x = 2.000000
   y = 1.000000
   z = 3.000000

🟢 Solução pelo numpy.linalg.solve:
   x = 2.000000
   y = 1.000000
   z = 3.000000

✅ Resultados coincidem? True


### Análise do Desafio

O algoritmo resolve corretamente o segundo sistema, retornando $x = 1,\ y = 2,\ z = 3$ — idêntico ao resultado do numpy. Isso demonstra que a implementação é genérica e funciona para qualquer sistema com **solução única** (matriz $A$ não-singular).

---
## 🔬 Parte 6 — Investigação: Sistema Problemático

### Sistema:
$$
\begin{cases}
x + y = 2 \\
2x + 2y = 4
\end{cases}
$$

In [5]:
A3 = [
    [1, 1],
    [2, 2]
]
b3 = [2, 4]

print("Sistema singular: x + y = 2 | 2x + 2y = 4")
print()

try:
    sol_gauss_3 = eliminacao_gauss(A3, b3)
    print("Solução encontrada:", sol_gauss_3)
except ValueError as e:
    print(f"⚠️  Erro capturado: {e}")

print()
print("Determinante da matriz A:", np.linalg.det(A3))

try:
    print("numpy.linalg.solve:", np.linalg.solve(A3, b3))
except np.linalg.LinAlgError as e:
    print(f"⚠️  numpy também falha: {e}")

Sistema singular: x + y = 2 | 2x + 2y = 4

Matriz aumentada inicial [A|b]:
[[1. 1. 2.]
 [2. 2. 4.]]

Após zerar coluna 1:
[[1. 1. 2.]
 [0. 0. 0.]]

⚠️  Erro capturado: Pivô nulo na coluna 1! O sistema pode ser singular ou ter infinitas soluções.

Determinante da matriz A: 0.0
⚠️  numpy também falha: Singular matrix


### Análise — Perguntas

**1. O que acontece com o algoritmo?**  
Após a primeira etapa de eliminação, o pivô da segunda coluna se torna **zero**. O algoritmo detecta isso e lança um erro, pois a divisão por zero tornaria o resultado inválido.

**2. O sistema possui solução única?**  
Não. A segunda equação é exatamente o dobro da primeira — são retas coincidentes. O sistema possui **infinitas soluções**: qualquer par $(x, y)$ com $x + y = 2$ é válido.

**3. Como identificar esse caso?**  
Há três formas:
- **Determinante:** $\det(A) = 0$ indica matriz singular (sem solução única).
- **Pivô nulo:** durante a eliminação, se um pivô for zero (ou próximo de zero), o sistema é singular.
- **Posto da matriz:** se $\text{rank}(A) < n$, o sistema é indeterminado ou inconsistente.

```python
# Verificação prática:
print(np.linalg.matrix_rank(A3))  # retorna 1, menor que n=2
```

In [6]:
print("Posto (rank) da matriz A3:", np.linalg.matrix_rank(A3))
print("→ rank < n, portanto o sistema NÃO tem solução única.")

Posto (rank) da matriz A3: 1
→ rank < n, portanto o sistema NÃO tem solução única.


---
## 🧠 Parte 7 — Reflexão Final

**1. Por que o método de Gauss funciona?**  
O método aplica **operações elementares sobre linhas** (multiplicar por escalar, somar linhas), que não alteram o conjunto de soluções do sistema. Ao transformar a matriz em forma triangular superior, cada equação passa a ter apenas uma incógnita a mais que a anterior — o que permite resolução direta por substituição regressiva, da última equação até a primeira.

**2. Onde sistemas lineares aparecem na engenharia?**  
Em praticamente todas as áreas:
- **Estruturas:** cálculo de forças em treliças e pórticos (Método dos Elementos Finitos)
- **Circuitos elétricos:** análise de malhas e nós (Leis de Kirchhoff)
- **Mecânica dos fluidos:** simulação de escoamentos (CFD)
- **Controle:** modelagem de sistemas dinâmicos
- **Processamento de sinais e imagens:** filtragem, compressão
- **Machine Learning:** regressão linear, mínimos quadrados

**3. Qual a importância de resolver sistemas grandes?**  
Problemas reais podem envolver milhares ou milhões de variáveis (simulações estruturais, climáticas, de tráfego). A eficiência do algoritmo é crítica: a Eliminação de Gauss tem complexidade $O(n^3)$, o que se torna muito custoso para $n$ grande. Por isso surgem métodos mais eficientes como fatoração LU, métodos iterativos (Gauss-Seidel, Gradiente Conjugado) e computação paralela.

---
## 📋 Resumo dos Resultados

| Sistema | Gauss | numpy | Coincidem? |
|---|---|---|---|
| Parte 1: $x=2, y=3, z=-1$ | ✅ | ✅ | ✅ |
| Parte 5 (Desafio): $x=1, y=2, z=3$ | ✅ | ✅ | ✅ |
| Parte 6 (Singular): infinitas soluções | ⚠️ Erro detectado | ⚠️ Erro | — |

> **Conclusão:** O método de Eliminação de Gauss implementado resolve corretamente sistemas com solução única e identifica adequadamente os casos singulares.